### ISSUE TITLE
Setup accelerometer

### ISSUE THREAD

**Issue by wiktorwieclaw** [grupacosmo/cansat#37]
We are going to use LIS3DH 3-axis I2C/SPI digital accelerometer, there already exists a driver implemented - [list3dh](https://crates.io/crates/lis3dh). We'll probably want to use I2C. Possibly shared with BME280, if there is a sound safe abstraction for shared i2c bus in Rust already.

**Comment by wiktorwieclaw** [comment]
See `embedded-hal-bus`, it allows sharing I2C in a safe manner.

**Comment by wiktorwieclaw** [comment]
[embedded-hal-bus](https://github.com/rust-embedded/embedded-hal/tree/master/embedded-hal-bus) doesn't support bus hsaring yet. For the time being, we can use [setup-bus](https://github.com/Rahix/shared-bus). See [shared-bus-example](https://github.com/ryan-summers/shared-bus-example).

**Comment by wiktorwieclaw** [comment]
Since I already got a hang of `shared_bus` I actually went ahead and made a [PR](https://github.com/grupacosmo/cansat/pull/41) that inits the shared bus. Feel free to continue working on it.

**Comment by Bartosz-Slowik** [comment]
I used your suggestion but wrote it based on newer main version.
