### ISSUE TITLE
Instructions in README wont work without config file

### ISSUE THREAD

**Issue by Bartosz-Slowik** [grupacosmo/cansat#8]
Since we no longer use runner in config file it should be the same for everyone and there is little reason to keep it in gitignore

**Comment by wiktorwieclaw** [comment]
We are not supposed to have a `.cargo/config.toml` file in the workspace root anymore. Each binary crate is supposed to have it's own config:
* `cansat-stm32f446/.cargo/config.toml`

We can remove it from the `.gitignore` now, but do not add a new config.
